/*
 * generated by Xtext
 */
package de.nordakademie.xconfigurator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XconfiguratorStandaloneSetup extends XconfiguratorStandaloneSetupGenerated{

	public static void doSetup() {
		new XconfiguratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

