/*
 * generated by Xtext
 */
package de.nordakademie.xconfigurator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XconfiguratorRuntimeModule extends de.nordakademie.xconfigurator.AbstractXconfiguratorRuntimeModule {

}
