/*
 * generated by Xtext
 */
package de.nordakademie.xconfigurator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XconfiguratorUiModule extends de.nordakademie.xconfigurator.ui.AbstractXconfiguratorUiModule {
	public XconfiguratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
