/*
 * generated by Xtext
 */
package de.nordakademie.xconfigurator.ui.contentassist

import de.nordakademie.xconfigurator.ui.contentassist.AbstractXconfiguratorProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XconfiguratorProposalProvider extends AbstractXconfiguratorProposalProvider {
}
